// Import all Radix icons used in BHG Edge
import {
  DashboardIcon,
  HomeIcon,
  FileIcon,
  FileTextIcon,
  TargetIcon,
  CodeIcon,
  ArchiveIcon,
  ChatBubbleIcon,
  GearIcon,
  ArrowUpIcon,
  PersonIcon,
  BarChartIcon,
  Share2Icon,
  EnvelopeClosedIcon,
  CalendarIcon,
  StarIcon,
  LightningBoltIcon,
  DesktopIcon,
  PieChartIcon,
  TableIcon,
  CubeIcon,
  ExitIcon,
  HamburgerMenuIcon,
  Cross1Icon,
  MagnifyingGlassIcon,
  PlusIcon,
  Pencil1Icon,
  EyeOpenIcon,
  CopyIcon,
  TrashIcon,
  ChevronDownIcon,
  CheckCircledIcon,
  ExclamationTriangleIcon,
  InfoCircledIcon,
  ExternalLinkIcon,
  MoonIcon,
  SunIcon,
  BookmarkIcon,
  ActivityLogIcon,
  BoxIcon,
  CheckboxIcon,
  ArrowLeftIcon,
  Share1Icon,
} from "@radix-ui/react-icons";

// Re-export for use in other components
export {
  DashboardIcon,
  HomeIcon,
  FileIcon,
  FileTextIcon,
  TargetIcon,
  CodeIcon,
  ArchiveIcon,
  ChatBubbleIcon,
  GearIcon,
  ArrowUpIcon,
  PersonIcon,
  BarChartIcon,
  Share2Icon,
  EnvelopeClosedIcon,
  CalendarIcon,
  StarIcon,
  LightningBoltIcon,
  DesktopIcon,
  PieChartIcon,
  TableIcon,
  CubeIcon,
  ExitIcon,
  HamburgerMenuIcon,
  Cross1Icon,
  MagnifyingGlassIcon,
  PlusIcon,
  Pencil1Icon,
  EyeOpenIcon,
  CopyIcon,
  TrashIcon,
  ChevronDownIcon,
  CheckCircledIcon,
  ExclamationTriangleIcon,
  InfoCircledIcon,
  ExternalLinkIcon,
  MoonIcon,
  SunIcon,
  BookmarkIcon,
  ActivityLogIcon,
  BoxIcon,
  CheckboxIcon,
  ArrowLeftIcon,
  Share1Icon,
};

// Map icon names to components for dynamic usage
export const iconMap = {
  Dashboard: DashboardIcon,
  Home: HomeIcon,
  File: FileIcon,
  FileText: FileTextIcon,
  Target: TargetIcon,
  Code: CodeIcon,
  Archive: ArchiveIcon,
  ChatBubble: ChatBubbleIcon,
  Gear: GearIcon,
  ArrowUp: ArrowUpIcon,
  Person: PersonIcon,
  BarChart: BarChartIcon,
  BarChart2: BarChartIcon,
  Share2: Share2Icon,
  Share: Share1Icon,
  EnvelopeClosed: EnvelopeClosedIcon,
  Calendar: CalendarIcon,
  Star: StarIcon,
  LightningBolt: LightningBoltIcon,
  Desktop: DesktopIcon,
  PieChart: PieChartIcon,
  Table: TableIcon,
  Cube: CubeIcon,
  Exit: ExitIcon,
  HamburgerMenu: HamburgerMenuIcon,
  Cross1: Cross1Icon,
  MagnifyingGlass: MagnifyingGlassIcon,
  Plus: PlusIcon,
  Pencil1: Pencil1Icon,
  EyeOpen: EyeOpenIcon,
  Copy: CopyIcon,
  Trash: TrashIcon,
  ChevronDown: ChevronDownIcon,
  CheckCircled: CheckCircledIcon,
  ExclamationTriangle: ExclamationTriangleIcon,
  InfoCircled: InfoCircledIcon,
  ExternalLink: ExternalLinkIcon,
  Moon: MoonIcon,
  Sun: SunIcon,
  Package: BoxIcon,
  Bookmark: BookmarkIcon,
  BookOpen: FileTextIcon,
  Briefcase: ArchiveIcon,
  Server: DesktopIcon,
  Activity: ActivityLogIcon,
  Box: BoxIcon,
  Cpu: CodeIcon,
  CheckSquare: CheckboxIcon,
  Folder: FileIcon,
  Lifebuoy: PersonIcon,
  MessageSquare: ChatBubbleIcon,
  TrendingUp: ArrowUpIcon,
  Database: TableIcon,
  DollarSign: CubeIcon,
  Settings: GearIcon,
  Users: PersonIcon,
  Zap: LightningBoltIcon,
  Share1: Share1Icon,
};

export type IconName = keyof typeof iconMap;

export function getIcon(name: string) {
  return iconMap[name as IconName] || DashboardIcon;
}
